#!/usr/bin/env python3
"""Emit the three child-relation sets a schema-driven query analyzer needs.

Derived from grammar.json (which `generate` already holds in memory) plus
node-types.json for field information:

  mandatory children  intersection across CHOICE  -> per-step guarantees
  possible children   union                       -> rejection by child-set
  precedence pairs    ordered (x,y) pairs         -> rejection by ordering

Hidden rules (leading underscore) are inlined, since they do not appear as
nodes in the tree; their children surface as children of the enclosing node.

Output is a C header keyed by *name*, resolved to TSSymbol at load time. Names
rather than ids deliberately: symbol ids move whenever a grammar is
regenerated, and a stale id is still a valid id, i.e. silently wrong.

  usage: gen_schema.py <grammar-dir> <c-identifier> > schema_<lang>.h
"""
import json, sys, os

def load(d):
    g = json.load(open(os.path.join(d, "grammar.json")))
    try:
        nt = {n["type"]: n for n in json.load(open(os.path.join(d, "node-types.json")))}
    except Exception:
        nt = {}
    return g["rules"], nt

def analyse(rules, node, stack, depth=0):
    """-> (all-symbols, mandatory-symbols, precedence-pairs)"""
    if depth > 60 or node is None:
        return set(), set(), set()
    t = node.get("type")
    if t == "STRING":
        return {node["value"]}, {node["value"]}, set()
    if t == "PATTERN":
        return set(), set(), set()
    if t == "BLANK":
        return set(), set(), set()
    if t == "SYMBOL":
        n = node["name"]
        # Hidden rules are inlined into the parent: recurse rather than naming them.
        if n.startswith("_") and n in rules and n not in stack:
            return analyse(rules, rules[n], stack | {n}, depth + 1)
        return {n}, {n}, set()
    if t == "SEQ":
        alls, mand, prs, seen = set(), set(), set(), []
        for m in node["members"]:
            a, mm, p = analyse(rules, m, stack, depth + 1)
            prs |= p
            for prev in seen:
                prs |= {(x, y) for x in prev for y in a}
            seen.append(a)
            alls |= a
            mand |= mm
        return alls, mand, prs
    if t == "CHOICE":
        alls, prs = set(), set()
        mands = []
        for m in node["members"]:
            a, mm, p = analyse(rules, m, stack, depth + 1)
            alls |= a
            prs |= p
            mands.append(mm)
        return alls, (set.intersection(*mands) if mands else set()), prs
    if t in ("REPEAT", "REPEAT1"):
        a, mm, p = analyse(rules, node["content"], stack, depth + 1)
        # A repetition admits any order among its own members.
        return a, (mm if t == "REPEAT1" else set()), p | {(x, y) for x in a for y in a}
    if t == "ALIAS":
        # The alias is what appears in the tree; the underlying symbol does not.
        v = node.get("value")
        if v:
            return {v}, {v}, set()
        return analyse(rules, node.get("content"), stack, depth + 1)
    if t in ("PREC", "PREC_LEFT", "PREC_RIGHT", "PREC_DYNAMIC",
             "TOKEN", "IMMEDIATE_TOKEN", "FIELD"):
        return analyse(rules, node.get("content"), stack, depth + 1)
    return set(), set(), set()

def cstr(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'

def main():
    d, ident = sys.argv[1], sys.argv[2]
    rules, nt = load(d)

    entries = []
    for name, rule in rules.items():
        if name.startswith("_"):
            continue                       # hidden: never a node in the tree
        alls, mand, prs = analyse(rules, rule, {name})
        alls = {a for a in alls if not a.startswith("_")}
        mand = {a for a in mand if not a.startswith("_")}
        prs = {(x, y) for x, y in prs if not x.startswith("_") and not y.startswith("_")}
        if not alls:
            continue
        idx = {s: i for i, s in enumerate(sorted(alls))}
        entries.append((name, sorted(alls), sorted(mand), sorted(prs), idx))

    out = sys.stdout
    w = out.write
    w("// GENERATED by tools/query-profiler/gen_schema.py -- do not edit.\n")
    w("// Child relations per node type, for a schema-driven query analyzer.\n\n")
    w("typedef struct {\n"
      "  const char *name;\n"
      "  const char *const *all;      uint16_t all_count;\n"
      "  const char *const *mandatory; uint16_t mandatory_count;\n"
      "  const uint16_t *prec;        uint16_t prec_count;   // pairs of indices into `all`\n"
      "} SchemaNode;\n\n")

    for i, (name, alls, mand, prs, idx) in enumerate(entries):
        w(f"static const char *const s{i}_all[] = {{{', '.join(cstr(a) for a in alls)}}};\n")
        if mand:
            w(f"static const char *const s{i}_man[] = {{{', '.join(cstr(a) for a in mand)}}};\n")
        if prs:
            flat = ", ".join(f"{idx[x]},{idx[y]}" for x, y in prs)
            w(f"static const uint16_t s{i}_prec[] = {{{flat}}};\n")

    w(f"\nstatic const SchemaNode {ident}_schema[] = {{\n")
    for i, (name, alls, mand, prs, idx) in enumerate(entries):
        m = f"s{i}_man, {len(mand)}" if mand else "NULL, 0"
        p = f"s{i}_prec, {len(prs)}" if prs else "NULL, 0"
        w(f"  {{{cstr(name)}, s{i}_all, {len(alls)}, {m}, {p}}},\n")
    w("};\n")
    w(f"static const unsigned {ident}_schema_count = {len(entries)};\n")

    tot_all = sum(len(a) for _, a, _, _, _ in entries)
    tot_prec = sum(len(p) for _, _, _, p, _ in entries)
    w(f"\n// {len(entries)} node types, {tot_all} child entries, {tot_prec} precedence pairs\n")
    print(f"[gen_schema] {ident}: {len(entries)} node types, {tot_all} child entries, "
          f"{tot_prec} precedence pairs", file=sys.stderr)

if __name__ == "__main__":
    main()
